### ISSUE TITLE
Cannot generate an add-on

### ISSUE THREAD

**Issue by kazoompa** [Textalk/generator-angular-schema-form-add-on#10]
Hi,

I have:

```
yo (1.8.3)
npm (2.14.2)
node (v4.0.0)
ubuntu 14.04
```

I cannot easily upgrade the above since I have other projects depending on them.

When I run _yo_ inside my add-on directory, I choose the add-on option and provide a name. Once I get to choose Input or Empty I get the error below:

```
TypeError: Cannot set property 'name' of undefined
    at null.<anonymous> (/usr/lib/node_modules/generator-angular-schema-form-add-on/app/index.js:48:23)
    at null.<anonymous> (/usr/lib/node_modules/generator-angular-schema-form-add-on/node_modules/yeoman-generator/lib/base.js:233:7)
```

Any help is greatly appreciated.

**Comment by kyse** [comment]
Got the same error last night.  Whatever they have published must be for some old version of yoeman generator?  What you get with npm install generator-angular-schema-form-add-on is not whats in either the master or develop branch.  Hell, this github repo doesn't even have a 0.1.3 version yet that's whats being pulled down from the npm repo.

Followed these steps to get a working solution:
1. Clone or Fork then Clone this repository to your local pc.
2. Open bash to the clone'd dir.
3. Init the npm/bower repo for the clone:
   1. `npm install`
   2. `bower install`
4. Compile the npm generator:
   1. `npm compile`
5. Link the local generator with yoeman.
   1. `npm link`
6. Head back to your add-on directory you created, and run the generator successfully.

**Comment by kornosaurus** [comment]
Something seems to be weird with the version published to npm, don't know how or when. But since the move to the json-schema-form, we would like to publish under that organization instead.. I will however look into publishing a new working version as fast as possible!

**Comment by kornosaurus** [comment]
New version is published! Should now work as expected

**Comment by kazoompa** [comment]
I confirm, thank you @kornosaurus.
