### ISSUE TITLE
Is the test folder misleading?

### ISSUE THREAD

**Issue by Anthropic** [Textalk/generator-angular-schema-form-add-on#5]
I opened the folder expecting spec file examples and found what the main ASF repo puts in a folder called example, would it make more sense to call it demo or example rather than test?

A standard best practise way to write jasmine tests could be included in a test folder instead perhaps.

**Comment by kornosaurus** [comment]
This sounds lika a good idea! Will do this for 0.1.4

**Comment by Anthropic** [comment]
:+1: sweet!

**Comment by kornosaurus** [comment]
This is currently in develop branch.. will release with some package.json and bower.json improvements as a patch release!
