### ISSUE TITLE
Fix gulp minification order.

### ISSUE THREAD

**Issue by Dervisevic** [Textalk/generator-angular-schema-form-add-on#7]
If you have more js files they're all just being globbed by alphabetic order. This means that the "module" file can come after a directive or service and then you get no module errors.

**Comment by kornosaurus** [comment]
This is currently in the develop branch

**Comment by kornosaurus** [comment]
Fixed in [e5d0b357](https://github.com/json-schema-form/generator-angular-schema-form-add-on/commit/e5d0b357d628d803abcc264de9298e33aeeaa0d0)
