### ISSUE TITLE
Filename mismatch

### ISSUE THREAD

**Issue by engelfrost** [Textalk/generator-angular-schema-form-add-on#8]
`gulp minify` creates a file called `/dist/asf-addon.js`, but `/demo/index.html` requests `/dist/<addon-name>.js`.

**Comment by kornosaurus** [comment]
This is only in the develop branch.

**Comment by kornosaurus** [comment]
Fixed in [e5d0b357](https://github.com/json-schema-form/generator-angular-schema-form-add-on/commit/e5d0b357d628d803abcc264de9298e33aeeaa0d0)
